name: Run Bazel tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    needs: Explore-GitHub-Actions
    steps:
    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
    - name: Use Bazel
      run: bazel test //...
