name: Run Bazel tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: where am I
        run: ls
      - name: Use Bazel
        run: bazel test //...
